- name: Terminate instances
  hosts: localhost
  tasks:

    - name: Terminate instances that were previously launched
      amazon.aws.ec2_instance:
        state: 'absent'
        instance_ids: i-04fc17c4588695bd2
