- name: Terminate instances
  hosts: localhost
  tasks:
    - name: List EC2 instances
      amazon.aws.ec2_instance_info:
        filters:
          instance-state-name: running #[ "shutting-down", "stopping", "stopped" ]
      register: ec2_info
    - name: Display EC2 instance IDs
      debug:
        msg: "{{ item.instance_id }}"
      loop: "{{ ec2_info.instances }}"

    - name: Terminate instances that were previously launched
      amazon.aws.ec2_instance:
        state: 'absent'
        instance_ids: "{{ item.instance_id }}"
      loop: "{{ ec2_info.instances }}"

