---
- name: "Variables in Ansible"
  hosts: dev
  vars:
    age: 20
    employee:
      team: "sysops"
      emp_id: 10022
  vars_files:
    - /home/atansible/automation/myvarfile.yml
  tasks:
    - name: "Ansible Simple Variable Example Usage"
      debug:
        msg: "Ansible Simple Variable Example Usage !!!"
    - name: "Print age"
      debug:
        msg: "My age is {{ age}}"
    - name: "Print from dictionary"
      debug:
        msg: "Employee team is {{ employee.team}} and employee id is {{ employee.emp_id}}"
    - name: "Using Jinja2 Filters"
      debug:
        msg: " {{[1,3,6,8,2,9] | select('odd')}}"
    - name: "Using Jinja2 Filters"
      debug:
        msg: " {{[1,3,6,8,2,9] | sort}}"
    - name: "Calling variables from file"
      debug:
        msg: "My name is {{ name }}"

    - name: "Variables from ansible facts"
      debug:
        msg: "{{ansible_all_ipv4_addresses}}"
