---
- name: Ensure /etc/udev/rules.d/99-asmdevices.rules exists
  file:
    path: /etc/udev/rules.d/99-asmdevices.rules
    state: touch

- name: Get disk serial number
  shell: udevadm info /dev/{{ item.partition }} | awk -F= '/ID_SERIAL=/ {print $2}'
  register: disk_serial_results
  loop: "{{ asm_disks }}"
  loop_control:
    loop_var: item
  when: item.partition != ''

- name: Add disk serial to udev rules
  lineinfile:
    path: /etc/udev/rules.d/99-asmdevices.rules
    line: 'KERNEL=="sd*", ENV{ID_SERIAL}=="{{ item.stdout.strip() }}", SYMLINK+="oracleasm/disks/{{ item.item.name }}", OWNER="oracle", GROUP="dba", MODE="0660"'
    state: present
  loop: "{{ disk_serial_results.results }}"
  loop_control:
    loop_var: item
  when: item.stdout is defined

- name: Prepare ASM disk group directory
  file:
    path: /dev/oracleasm/disks
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Reload UDEV rules
  command: udevadm control --reload-rules

- name: Trigger UDEV to create ASM disk symlinks
  command: udevadm trigger

- name: Verify ASM disks in /dev/oracleasm/disks
  command: ls -l /dev/oracleasm/disks/
  register: asm_disk_links

- name: Display ASM disk symlinks
  debug:
    var: asm_disk_links.stdout

[root@rhel8 ansible]#
[root@rhel8 ansible]#
[root@rhel8 ansible]#
[root@rhel8 ansible]# cat oracle_install/tasks/config_asmdisks.yml
---
- name: Ensure /etc/udev/rules.d/99-asmdevices.rules exists
  file:
    path: /etc/udev/rules.d/99-asmdevices.rules
    state: touch

- name: Get disk serial number
  shell: udevadm info /dev/{{ item.partition }} | awk -F= '/ID_SERIAL=/ {print $2}'
  register: disk_serial_results
  loop: "{{ asm_disks }}"
  loop_control:
    loop_var: item
  when: item.partition != ''

- name: Add disk serial to udev rules
  lineinfile:
    path: /etc/udev/rules.d/99-asmdevices.rules
    line: 'KERNEL=="sd*", ENV{ID_SERIAL}=="{{ item.stdout.strip() }}", SYMLINK+="oracleasm/disks/{{ item.item.name }}", OWNER="oracle", GROUP="dba", MODE="0660"'
    state: present
  loop: "{{ disk_serial_results.results }}"
  loop_control:
    loop_var: item
  when: item.stdout is defined

- name: Prepare ASM disk group directory
  file:
    path: /dev/oracleasm/disks
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Reload UDEV rules
  command: udevadm control --reload-rules

- name: Trigger UDEV to create ASM disk symlinks
  command: udevadm trigger

- name: Verify ASM disks in /dev/oracleasm/disks
  command: ls -l /dev/oracleasm/disks/
  register: asm_disk_links

- name: Display ASM disk symlinks
  debug:
    var: asm_disk_links.stdout
