---
- name: Ensure groups exist
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    state: present
  loop: "{{ groups_list }}"

- name: Ensure oracle user exists and is added to all specified groups
  user:
    name: oracle
    uid: 54321
    group: oinstall
    groups: "{{ groups_list | map(attribute='name') | join(',') }}"
    append: yes
    state: present

- name: Ensure the home directory exists for oracle
  file:
    path: /home/oracle
    state: directory
    owner: oracle
    group: oinstall
    mode: '0755'

- name: Copy configuration files to oracle user's home directory
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: oracle
    group: oinstall
    mode: '0644'
  vars:
    oracle_hostname: "{{ ansible_fqdn }}"
    oracle_sid: "{{ oracle_sid }}"
  loop:
    - { src: 'bash_profile.j2', dest: '/home/oracle/.bash_profile' }
    - { src: 'grid_env.j2', dest: '/home/oracle/grid_env' }
    - { src: 'db_env.j2', dest: '/home/oracle/db_env' }

- name: Create directories for Oracle
  file:
    path: "{{ item }}"
    state: directory
    mode: '0775'
  loop:
    - /u02/sources
    - /u01/app/19.0.0/grid
    - /u01/app/oracle/product/19.0.0/dbhome_1

- name: Change ownership and set permissions for /u01
  file:
    path: /u01
    owner: oracle
    group: oinstall
    mode: '0775'
    recurse: yes

